name: pokemon_hub_flutter
description: PocketChase app
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0
  image_picker: ^1.2.2
  google_mlkit_text_recognition: ^0.15.1
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2
  path_provider: ^2.1.5
  camera: ^0.12.0+1
  image: ^4.2.0
  cloud_functions: ^6.2.0
  firebase_storage: ^13.3.0
  mime: ^2.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/pocketdex_icon.png
  adaptive_icon_background: "#FFD21F"
  adaptive_icon_foreground: assets/images/pocketdex_icon.png
  remove_alpha_ios: true
  min_sdk_android: 21
